/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    
    val array = arrayOf(1, 3, 5, 7)

    val mixArray = arrayOf(1, 3, 5, 7 , "Dicoding" , true)

    //  Array dengan tipe data primitif 

    // intArrayOf() : IntArray
    // booleanArrayOf() : BooleanArray
    // charArrayOf() : CharArray
    // longArrayOf() : LongArray
    // shortArrayOf() : ShortArray
    // byteArrayOf() : ByteArray


    val intArray = intArrayOf(1, 3, 5, 7)
    println(intArray[2])

    /*
    Output: 5
    */

    intArray[2] = 11  // [1, 3, 11, 7]

    println(intArray[2])

    /*
        Output: 11
    */
}
