/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    
    val character = 'A'
    // val character: Char = 'ABC'   // Incorrect character literal
    println(character)

    var vocal = 'A'
 
    println("Vocal " + vocal++)
    println("Vocal " + vocal++)
    println("Vocal " + vocal++)
    println("Vocal " + vocal--)
    println("Vocal " + vocal--)
    println("Vocal " + vocal--)
    println("Vocal " + vocal--)

    // Unicode A = 0041 and B = 0042 
}
