/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

import kotlin.random.Random

// import kotlin.math.PI
// import kotlin.math.cos
// import kotlin.math.sqrt

import kotlin.math.*

fun main() {
    // Import dan Packages

    // Seluruh konten pada Kotlin, seperti kelas dan fungsi, dibungkus dalam sebuah package. Package tersebut digunakan untuk mengelompokkan kelas, fungsi dan variabel yang mempunyai kemiripan fungsionalitas. Untuk menggunakan kelas, fungsi maupun variabel yang berada pada suatu package, kita harus menuliskan secara lengkap alamat package tersebut. Sebagai contoh kita akan menggunakan kelas Random, maka kita harus menuliskan seperti ini:

    // val someInt = kotlin.random.Random(0).nextInt(1, 10)

    // Kode tersebut menunjukkan bahwa kelas Random berada pada package kotlin.random, tetapi apakah perlu menuliskan kode sepanjang itu untuk menggunakan sebuah kelas? Tentu tidak, untuk meminimalisir hal tersebut kita cukup mengimpor package kelas Random. Dengan begitu kita tidak perlu menuliskan kode yang panjang secara berulang.


    // Importing Package

    // Untuk mengimpor suatu package kelas, fungsi atau variabel, kita cukup menuliskan keyword import kemudian dilanjutkan dengan alamat spesifiknya seperti: 

    // import packagename.ClassName
    // import packagename.functionName
    // import packagename.propertyName

    // Karena kelas Random berada pada package kotlin.random, maka penulisannya menjadi seperti ini:
    // import kotlin.random.Random
 
    val someInt = Random(0).nextInt(1, 10)

    // package kotlin.math

    // import kotlin.math.PI
    // import kotlin.math.cos
    // import kotlin.math.sqrt

    // println(PI)
    // println(cos(120.0))
    // println(sqrt(9.0))


    // Kita juga dapat mengganti nama sebuah kelas, fungsi atau variabel yang kita import dengan menggunakan alias yang direpresentasikan dengan kata kunci as.
    // import kotlin.math.PI
    // import kotlin.math.cos as cosinus
    // import kotlin.math.sqrt as akar


    // println(PI)
    // println(cosinus(120.0))
    // println(akar(9.0))


    // Kita dapat mengimpor seluruh kelas, fungsi dan variabel yang berada pada suatu package dengan menggunakan tanda  * pada akhir package tersebut.

    // import kotlin.math.*
}