/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    // Membuat Package Baru
    // Seperti yang diketahui sebelumnya, package merupakan pembungkus dari kelas (package-level class), fungsi (package-level function) atau variabel (package-level variable) berfungsi serupa. Kita juga sudah mengetahui cara mengimpor suatu kelas, fungsi atau variabel yang terdapat pada sebuah package. Namun kita belum tahu bagaimana package tersebut dibuat. Jadi pada pembahasan kali ini kita akan mencoba bagaimana untuk membuat sebuah package pada Kotlin.

    // Idealnya sebuah package pada Kotlin dituliskan dengan awalan nama domain perusahaan yang dibalik. Contoh, com.dicoding. Kemudian diikuti dengan nama package yang akan digunakan.

    // Untuk membuat sebuah package kita perlu membuat folder package pada berkas proyek. Perhatikan Project Tool Window yang terdapat pada IntelliJ Idea. Klik kanan pada folder src kemudian arahkan pada menu New > package.

    // Setelah itu ketikkan nama package yang akan kita buat, misalnya "com.dicoding.oop.utils".

    // Perlu diingat bahwa penamaan package selalu dituliskan dengan flatcase, tanpa garis bawah dan dipisahkan dengan titik.

    // Selanjutnya, buatlah sebuah berkas di dalam package utils. Disini kita menamai berkas tersebut dengan nama MyMath.kt. Bukalah berkas tersebut dan perhatikan baris kode yang dihasilkan oleh IntelliJ Idea. Seharusnya kita melihat baris kode berikut pada berkas MyMath.kt.

    /*
    
    package com.dicoding.oop.utils

    fun sayHello() = println("Hello From package com.dicoding.oop.utils")
    
    */


    /*

    calling
    fun main(){
        com.dicoding.oop.utils.sayHello()
    }

    or

    import com.dicoding.oop.utils.sayHello

    fun main() {
        sayHello()
    }

    
    */
}