/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

class Animal(var name: String, var weight: Double, var age: Int = 0, var isMammal: Boolean = true){
}

// Init block

// blok init yang memungkinkan kita untuk menuliskan properti di dalam body class ketika kita menggunakan primary constructor
// satu fungsi lainnya adalah untuk membantu dalam memvalidasi sebuah nilai properti sebelum diinisialisasi.

class Animal1(pName: String, pWeight: Double, pAge: Int, pIsMammal: Boolean){
    val name: String
    val weight: Double
    val age: Int
    val isMammal: Boolean
 
    init {
        weight = if(pWeight < 0) 0.1 else pWeight
        age = if(pAge < 0) 0 else pAge
        name = pName
        isMammal = pIsMammal
    }
}

// jika nama property class sama dengan parameter head class, maka gunakan this. untuk menginisialisasi properti 

class Animal2(name: String, weight: Double, age: Int, isMammal: Boolean) {
    val name: String
    val weight: Double
    val age: Int
    val isMammal: Boolean
 
    init {
        this.weight = if(weight < 0) 0.1 else weight
        this.age = if(age < 0) 0  else age
        this.name = name
        this.isMammal = isMammal
    }
}

fun main(){
    val dicodingCat = Animal("Dicoding Miaw", 4.2)
    println("Nama: ${dicodingCat.name}, Berat: ${dicodingCat.weight}, Umur: ${dicodingCat.age}, mamalia: ${dicodingCat.isMammal}" )

    val dicodingCat1 = Animal1("Dicoding Miaw", 4.2, 2, true)
    println("Nama: ${dicodingCat1.name}, Berat: ${dicodingCat1.weight}, Umur: ${dicodingCat1.age}, mamalia: ${dicodingCat1.isMammal}")
}