/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

// Exception
// Kode yang baik yaitu kode yang terhindar dari segala bentuk kejadian dengan efek buruk pada aplikasi kita. Kejadian tersebut pada programming disebut Exception. Hal terburuk yang disebabkan oleh exception ini adalah dapat terhentinya aplikasi ketika dijalankan. 

// Exception adalah event (kejadian) yang dapat mengacaukan jalannya suatu program. Pada Kotlin semua exception bersifat Unchecked, yang artinya exception terjadi karena kesalahan pada kode kita. Berikut ini beberapa contoh Unchecked Exception yang sering mengganggu jalannya program kita:

// - ArithmeticException
// - NumberFormatException
// - NullPointerException



fun main() {

    
    // ArithmeticException merupakan exception yang terjadi karena kita membagi suatu bilangan dengan nilai nol. Berikut merupakan contoh kode yang dapat membangkitkan ArithmeticException.

    val someValue = 6
    println(someValue / 0)

    /*
        output:
        Exception in thread "main" java.lang.ArithmeticException: / by zero
    */

    // NumberFormatException disebabkan karena terjadi kesalahan dalam format angka. Sebagai contoh, kita akan mengubah sebuah nilai String menjadi Integer tetapi nilai String yang akan kita ubah tidak memiliki format angka yang benar, sehingga dapat membangkitkan NumberFormatException. Berikut contoh kodenya:

    val someStringValue = "18.0"
    println(someStringValue.toInt())

    /*
        output:
        Exception in thread "main" java.lang.NumberFormatException: For input string: "18.0"
    */


    // Dan yang terakhir adalah NullPointerException atau NPE. Walaupun Kotlin memiliki operator Null Safety, NPE tetap bisa saja terjadi. NPE terjadi karena sebuah variabel atau objek memiliki nilai null, padahal seharusnya objek atau variabel tersebut tidak boleh null. Berikut contoh kasus yang dapat menyebabkan NullPointerException:

    val someNullValue: String? = null
    val someMustNotNullValue: String = someNullValue!!
    println(someMustNotNullValue)

    /*
    output:
        Exception in thread "main" kotlin.NullPointerException at MainKt.main(Main.kt:3)
    */
}