/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

abstract class Animal(var name: String, var weight: Double, var age: Int, var isCarnivore: Boolean){
 
    fun eat(){
        println("$name sedang makan !")
    }
 
    fun sleep(){
        println("$name sedang tidur !")
    }
}

class Cat(var pname: String = "Kucing", var pweight: Double = 2.2, var page: Int = 1, var pisCarnivore: Boolean = true) : Animal(pname, pweight, page, pisCarnivore)

fun main() {
    // Abstract Class

    // abstract merupakan gambaran umum dari sebuah kelas. Ia tidak dapat direalisasikan dalam sebuah objek.
    // konsep abstract class perlu diterapkan agar kelas Animal tidak dapat direalisasikan dalam bentuk objek namun tetap dapat menurunkan sifatnya kepada child class-nya.

    // val animal = Animal("dicoding animal", 2.6, 1, true)

    // Output: cannot create an instance of an abstract class

    val cat = Cat()
    println("Name : ${cat.name}. ")
    println("Weight : ${cat.weight}. ")
    println("Age : ${cat.age}. ")
    println("Carnivore : ${cat.isCarnivore}. ")
    println(cat.eat())


}