/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

// Nullable Receiver

// Menariknya, kita bisa juga mendeklarasikan sebuah extension dengan nullable receiver type. Alhasil, extension tersebut bisa dipanggil pada objek yang bahkan nilainya null.

/*

val Int?.slice: Int
    get() = if (this == null) 0 else this.div(2)

*/

// If expression pada contoh di atas adalah untuk memeriksa apakah receiver object-nya bernilai null. Jika tidak bernilai null, maka receiver object tersebut akan secara otomatis di-casting menjadi tipe non-null, sehingga kita bisa menggunakan nilainya.

// Selain menggunakan if expression, kita juga bisa menggunakan elvis operator. Misalnya seperti berikut:

val Int?.slice: Int
    get() = this?.div(2) ?: 0


val Int.slice1: Int
    get() = this.div(2)

fun main() {
    val value: Int? = null
 
    println(value.slice)

    // output : 0

    val value0: Int? = null
    val value1: Int? = null
 
    println(value0?.slice)
    println(value1?.slice)

    /*
        output : null
                null
    */


}