/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    // Special Class dan Collection
    // Special Class adalah Class yang memiliki karakteristik khusus atau fitur yang tidak tersedia di Class biasa (reguler).

    // class Abstract Class dan Interface, ada banyak Class khusus lain yang disediakan oleh Kotlin

    // Data Class: dirancang khusus untuk menyimpan data. Otomatis terdapat fungsi equals(), hashCode(), toString(), dan copy(). 
    // Nested Class: membuat Class di dalam Class tanpa akses ke kelas induk.
    // Inner Class: membuat Class di dalam Class dengan akses ke kelas induk.
    // Enum Class: tipe data dengan sekumpulan nilai konstan yang telah ditentukan.
    // Sealed Class: digunakan untuk pembatasan hierarki class.


    // Collection merupakan sebuah struktur data yang digunakan untuk menyimpan banyak nilai sekaligus. Hal ini tentunya penting karena dalam pembuatan aplikasi, sering kali kita dihadapkan dengan data yang banyak. Misalnya, seperti membuat aplikasi yang menampilkan daftar kontak, daftar produk, atau opsi pekerjaan pada menu dropdown. Di sinilah peran Collection guna mempermudah mengelola dan mengorganisasi data tersebut.

    // Kotlin menyediakan beberapa jenis Collection yang bervariasi, berikut di antaranya.

    // List: untuk menyimpan nilai bebas dengan index (boleh sama).
    // Set: untuk menyimpan nilai yang unik (tidak boleh sama).
    // Map: untuk menyimpan dengan format key to value (key tidak boleh sama).
}