/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    // Slice
    // Setelah pembahasan fungsi take() pada sub-modul sebelumnya, muncul pertanyaan, bagaimana jika kita ingin menyaring item dari posisi tertentu? Untuk itu kita bisa memanfaatkan fungsi slice(). Dalam penggunaannya, fungsi slice() membutuhkan sebuah argumen berupa Range yang digunakan untuk menentukan posisi pertama dan terakhir yang akan disaring. Berikut contohnya:

    val total = listOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
    val slice = total.slice(3..6)

    println(slice)

    /*
    output: [4, 5, 6, 7]
    */

    // Karena menggunakan Range, kita juga bisa menggunakan operator step ketika argumennya disematkan seperti berikut:

    // val total = listOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
    val slice1 = total.slice(3..6 step 2)

    println(slice1)

    /*
    output: [4, 6]
    */

    // Kemudian jika ingin menentukan posisi yang lebih spesifik, kita bisa mendefinisikannya di dalam sebuah collection, kemudian disematkan sebagai argumen. Misal seperti di bawah berikut:

    val index = listOf(2, 3, 5, 8)
    // val total = listOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
    val slice2 = total.slice(index)

    println(slice2)

    /*
        output: [3, 4, 6, 9]
        */

    // Kita harus berhati-hati dalam menentukan cakupan index untuk mendapatkan data. Karena dapat menyebabkan terjadinya ArrayIndexOutOfBoundsException jika posisi yang ditentukan tidak terdapat pada objek collection.
}