/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    // Chunked
    // Sama seperti fungsi split(), fungsi chunked() bisa kita gunakan untuk memecah nilai String menjadi beberapa bagian kecil dalam bentuk Array. Namun untuk penerapannya sedikit berbeda, di mana fungsi split() membutuhkan argumen berupa RegEx sebagai parameter sedangkan chunked() membutuhkan nilai yang akan digunakan sebagai jumlah indeks untuk pemisah. Contoh penggunaannya seperti berikut:


    val word = "QWERTY"
    val chunked = word.chunked(3)

    println(chunked)

    /*
    output:[QWE, RTY]
    */


    // Selain itu, kita juga bisa menggunakannya untuk memodifikasi setiap nilai yang sudah dipecah. Contoh, hasil dari nilai yang sudah dipecah ingin kita buat menjadi huruf kecil, maka kita bisa menggunakan fungsi chunked() seperti berikut: 

    // val word = "QWERTY"
    val chunkedTransform = word.chunked(3) {
        // it.toString().toLowerCase()
        // warning: 'fun String.toLowerCase(): String' is deprecated. Use lowercase() instead.
        it.toString().lowercase()
    }

    println(chunkedTransform)

    /*
    output: [qwe, rty]
    */

    // Argumen yang berada pada lambda expression di atas merepresentasikan setiap nilai yang sudah dipecah.
}