/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    
    /*
    Apa itu Control Flow?
    Ketika kita mengembangkan sebuah program, tentu kita harus tahu seperti apa alurnya. Control flow adalah cara kita mengontrol alur dari sebuah program berdasarkan kondisi saat program tersebut berjalan.

    If Expression merupakan salah satu bagian dari Control Flow.

    Terdapat beberapa bagian dari control flow yang akan kita pelajari, antara lain:

    When Expression
    Expression & Statement
    While and Do While
    Range and For Loop
    Break and Continue Labels
 */
}
