/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

data class DataUser(val name : String, val age : Int)

// menyalin object dengan function copy, dan bisa timpa properti

fun main() {
    val dataUser = DataUser("nrohmen", 17)
    val dataUser2 = DataUser("nrohmen", 17)
    val dataUser3 = DataUser("dimas", 24)
    val dataUser4 = dataUser.copy()
    // DataUser(name=nrohmen, age=17)
    println(dataUser4)
    
    val dataUser5 = dataUser.copy(age = 18)
    // DataUser(name=nrohmen, age=18)
    println(dataUser5)

}