/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

data class DataUser(val name : String, val age : Int){
    fun intro(){
        println("My name is $name, I am $age years old")
    }
}

fun main() {

    // Destructuring Declarations

    // Destructuring Declaration adalah proses memetakan objek menjadi sebuah variabel. Ini bisa dengan mudah kita lakukan pada data class. Dengan fungsi componentN() yang ada pada data class, kita bisa menguraikan sebuah objek menjadi beberapa properti yang dimilikinya. Sebagai contoh, kita ingin menguraikan objek dataUser:


    val dataUser = DataUser("nrohmen", 17)

    val name = dataUser.component1()
    val age = dataUser.component2()

    println("My name is $name, I am $age years old")

    // atau bisa seperti ini

    val (name1, age1) = dataUser

    println("My name is $name1, I am $age1 years old")

    // Kesimpulannya, seperti aspek - aspek lain dari Kotlin, data class bertujuan untuk mengurangi jumlah kode boilerplate yang Anda tuliskan. Dan perlu diketahui bahwa data class tidak hanya sekedar untuk mengelola properti yang ada di dalamnya. Ketika mempunyai data yang sangat kompleks, kita juga bisa menerapkan sebuah behaviour di dalam data class.

    dataUser.intro()
}