/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    // For dapat digunakan pada Ranges, Collections, Arrays dan apa pun yang menyediakan iterator

    val ranges = 1..5
    for (i in ranges){
        println("value is $i!")
    }

    println("=================")

    val ranges2 = 1.rangeTo(5)
    for (i in ranges2){
        println("value is $i!")
    }

    println("=================")

    // range expression

    val ranges3 = 1.rangeTo(10) step 3
    for (i in ranges3 ){
        println("value is $i!")
    }

    println("=================")

    // Kita juga dapat mengakses indeks untuk setiap elemen yang ada pada ranges dengan memanfaatkan fungsi withIndex()

    val ranges4 = 1.rangeTo(10) step 3
    for ((index, value) in ranges4.withIndex()) {
        println("value $value with index $index")
    }

    println("=================")

    // Dengan menggunakan forEach , kita tidak perlu lagi menggunakan for secara terpisah seperti sebelumnya. Ia akan otomatis melakukan perulangan pada setiap item dari variabel tersebut sampai akhir

    val ranges5 = 1.rangeTo(10) step 3
    ranges5.forEach { value ->
        println("value is $value!")
    }
}

