/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    val user = setUser("Alfian", 19)
    println(user)
 
    printUser("Alfian")
}


// fun functionName(param1: Type1, param2: Type2, ...): ReturnType {
//     return result
//     expression atau statemen
// }


// fun setUser(name: String, age: Int): String {
//     return "Your name is $name, and you $age years old"
// }

// jika satu expression bisa di ubah jadi expression body
// fun setUser(name: String, age: Int): String = "Your name is $name, and you $age years old"

// dengan expression body tidak perlu menentukan tipe nilai kembalian secara eksplisit
fun setUser(name: String, age: Int) = "Your name is $name, and you $age years old"

// jika tidak ingin mengembalikan nilai maka pake unit
fun printUser(name: String): Unit {
    print("Your name is $name")
}

// Ketika menggunakan tipe kembalian Unit, Kotlin memungkinkan kita untuk menghilangkannya. Kenapa demikian? Kompiler akan mendeteksinya sebagai tipe kembalian yang redundant:
// fun printUser(name: String) {
//     print("Your name is $name")
// }