/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    val fullName = getFullName(first = "Kotlin" , middle = " is ", last = "Awesome")
    println(fullName)

    // Menariknya lagi, kita bisa mengubah posisi dari argumen ketika dilampirkan, misalnya seperti ini:
    val fullName1 = getFullName(middle = " is " , first = "Kotlin", last = "Awesome")
    println(fullName1)

    // default argument
    val fullName2 = getFullName()
    println(fullName2)

    val fullName3 = getFullName(first = "Dicoding")
    println(fullName3)
}

// Named Argument
// Untuk mengatasi hal ini Kotlin menawarkan sebuah cara. Dengan ini, kita tak perlu lagi menghafal posisi dari sebuah parameter. Karena ketika sebuah fungsi dipanggil, kita bisa menentukan argumen dari parameter mana yang ingin dilampirkan dengan memanggil nama dari parameter tersebut. Misalnya kita mempunyai sebuah fungsi seperti berikut:
// fun getFullName(first: String, middle: String, last: String): String {
//     return "$first $middle $last"
// }

// Default Argument
// Tidak sampai di situ, Kotlin juga memungkinkan kita untuk menentukan nilai default dari sebuah parameter. Jika kita melewatkan argumen untuk dilampirkan, maka nilai default tersebut lah yang akan digunakan.

fun getFullName(
        first: String = "Kotlin", 
        middle: String = " is ", 
        last: String = "Awesome"): String {
    return "$first $middle $last"
}
