/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    // Mendeklarasikan Fungsi Generic
    // Setelah deklarasi generic pada sebuah kelas, sekarang kita akan belajar cara mendeklarasikan generic pada sebuah fungsi. Generic pada sebuah fungsi dibutuhkan ketika kita membuat sebuah fungsi yang berhubungan dengan List. Misalnya, list yang dapat digunakan untuk berbagai tipe dan tidak terpaku pada tipe tertentu. 

    // Fungsi generic memiliki tipe parameternya sendiri yang ditentukan ketika fungsi tersebut dipanggil. Cara mendeklarasikannya sedikit berbeda dengan kelas generic. Tipe parameter yang berada di dalam angle bracket harus ditempatkan sebelum nama fungsi yang ditentukan.
}