/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    
    val openHours = 7
    val now = 20
    if (now > openHours){
        println("office already open")
    }

    // val office: String
    // if (now > openHours) {
    //     office = "Office already open"
    // } else {
    //     office = "Office is closed"
    // }

    // println(office)

    val office: String
    office = if (now > 7) {
        "Office already open"
    } else if (now == openHours){
        "Wait a minute, office will be open"
    } else {
        "Office is closed"
    }

    println(office)

    // Perlu diketahui bahwa Kotlin tidak mendukung ternary operator (condition ? then : else), karena peran dari operator tersebut sudah digantikan dengan if expressions
}
