/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.Kotlin

fun main() {

    // Object Everywhere
    // Pada sub-modul Data Types telah disebutkan bahwa pada Kotlin semua bertindak sebagai objek di mana kita bisa memanggil member function dan properti dari sebuah variabel. Objek merupakan hasil realisasi dari sebuah blueprint atau class yang tentunya memiliki fungsi dan juga properti sama seperti blueprint-nya. Artinya, dengan membuat objek kita dapat mengakses fungsi dan properti yang terdapat pada kelas tersebut.

    // Pada Kotlin, nilai primitif seperti String, Integer, Char, Boolean merupakan sebuah Object. Hal ini berbeda dengan bahasa pemrograman lain. Maka dari itu, terdapat sebuah istilah yang terkenal di  Kotlin, yaitu “Object Everywhere”. Perhatikan kode berikut:
    val someString = "Dicoding"

    // Pada kode tersebut kita melakukan pembuatan variabel yang juga merupakan sebuah objek dengan nama someString. Objek tersebut merupakan realisasi dari kelas String, maka objek someString memiliki fungsi dan properti yang merupakan anggota dari kelas String.


    println(someString.reversed())
    println(someString.uppercase())
    println(someString.lowercase())


    val someString1 = "123"
    val someInt = someString1.toInt()
    val someOtherString = "12.34"
    val someDouble = someOtherString.toDouble()
 
    println(someInt is Int)
    println(someDouble is Double)
}