/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.Kotlin

fun main() {
    val rangeInt = 1..10
    // default step 1
    println(rangeInt.step)

    /*
    output: 1
    */

    val rangeInt2 = 1..10 step 2
    rangeInt2.forEach {
        print("$it ")
    }
    println(rangeInt2.step)

    /*
    output: 1 3 5 7 9 2
    */

    val rangeInt3 = 1.rangeTo(10)

    println(rangeInt3)

    // 1-10

    val downInt = 10.downTo(1)

    println(downInt)
    // 10, 9, 8, 7, 6, 5, 4, 3, 2, 1.

    val downInt2 = 10.downTo(1) step 2

    println(downInt2)


    // Kita juga bisa memeriksa apakah suatu nilai ada pada cakupan nilai Range


    val tenToOne = 10.downTo(1)
    if (7 in tenToOne) {
        println("Value 7 available")
    }

    // fungsi di atas sama hal nya dengan if expression di bawah inisialisasi

    // if (1 <= 7 && 7 <= 10){
    //     println("Value 7 available")
    // }


    // jika sebalik nya memeriksa suatu nilai tidak ada dalam cangkupan range

    val tenToOne2 = 10.downTo(1)
    if (11 !in tenToOne2) {
        println("No value 11 in Range ")
    }
}