/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.kotlin

fun main() {
    // var identifier: Type = initialization

    var company: String = "Dicoding"
    company = "Dicoding Academy"

    // val company: String = "Dicoding" // protected value
    // company = "Dicoding Academy" 		// Val cannot be reassigned
    println(company)

    val firstWord = "Dicoding "
    val lastWord = "Academy"
    println(firstWord + lastWord)

    val valueA: Int = 10
    val valueB = 20
    print(valueA + valueB)
}
