/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dicoding.Kotlin

fun main() {


    // while

    var counter = 1
    while (counter <= 7){
        println("Hello, World!")
        counter++
    }

    // While bersifat Entry Controlled Loop. Artinya, kondisi yang diberikan akan dievaluasi terlebih dahulu. Jika kondisi tersebut terpenuhi maka proses perulangan akan dijalankan.

    // Jika kondisi yang diberikan tidak terpenuhi sejak awal maka proses perulangan tidak akan dijalankan. Untuk mengujinya Anda bisa menulis dan menjalankan kode berikut:

    println("=====================")

    counter = 8
    while (counter <= 7){
        println("Hello, World!")
        counter++
    }


    println("=====================")

    // Do While
    counter = 1
    do {
        println("Hello, World!")
        counter++
    } while (counter <= 7)


    // Berbeda dengan While, Do While bersifat Exit Controlled Loop di mana proses perulangan akan langsung dijalankan di awal. Jika telah selesai, barulah kondisi yang diberikan akan dievaluasi.

    // Saat menggunakan While dan Do While perhatikan infinite loop, yaitu kondisi di mana proses perulangan berlangsung terus menerus sampai aplikasi menjadi crash. Contoh dari infinite loop adalah seperti berikut:

    /*
    
    var value = 'A'
    do {
        print(value)
    } while (value <= 'Z')
    
    */


    // Infinite loop terjadi jika kondisi yang diberikan selamanya terpenuhi atau bernilai true.

    // While dan Do While sendiri tidak dapat digunakan untuk melakukan perulangan pada rentan angka. Untuk melakukannya kita bisa menggunakan For Loop
}